import { SubmissionInput, useSubmission } from "../components/SubmissionInput";
import { useEffect, useState } from "react";
import { ArrowRight, ArrowUpRight, BookOpenCheck, BrainCircuit, Calculator, CalendarDays, Check, ChevronRight, Compass, GraduationCap, Languages, Lightbulb, MessageCircleMore, PenLine, RotateCcw, Search, Send, Sparkles, Target, Trophy } from "lucide-react";
import { api } from "../api";
import type { Navigate, PracticeStreak } from "../types";
import { StructuredResult } from "../components/ResultPanel";
import { Button, Card, ErrorBanner, Input, PracticeStreakCard, ScreenHeader, Segmented, Select, Tag, Textarea } from "../components/ui";
import { opportunities } from "../data/catalogs";

function openOfficial(url: string) { if (window.Telegram?.WebApp.openLink) window.Telegram.WebApp.openLink(url); else window.open(url, "_blank", "noopener,noreferrer"); }

const deadlines = [
  { school: "Stanford", mark: "S", round: "REA", date: "2026-11-01", display: "Nov 1", color: "coral", url: "https://admission.stanford.edu/apply/first-year/" },
  { school: "MIT", mark: "M", round: "Early Action", date: "2026-11-01", display: "Nov 1", color: "red", url: "https://mitadmissions.org/apply/firstyear/deadlines-requirements/" },
  { school: "Harvard", mark: "H", round: "Regular", date: "2027-01-01", display: "Jan 1", color: "wine", url: "https://college.harvard.edu/admissions/apply/application-requirements" },
  { school: "Yale", mark: "Y", round: "Regular", date: "2027-01-02", display: "Jan 2", color: "blue", url: "https://admissions.yale.edu/timelines" },
  { school: "Princeton", mark: "P", round: "Regular", date: "2027-01-01", display: "Jan 1", color: "wine", url: "https://admission.princeton.edu/apply/application-dates-deadlines" },
  { school: "Penn", mark: "P", round: "Regular", date: "2027-01-05", display: "Jan 5", color: "blue", url: "https://admissions.upenn.edu/how-to-apply/first-year-applicants" },
];

export function DiscoverScreen({ navigate }: { navigate: Navigate }) {
  const [filter, setFilter] = useState("All");
  const [query, setQuery] = useState("");
  const visible = opportunities.filter((item) => (filter === "All" || item.area === filter) && `${item.title} ${item.type} ${item.fit} ${item.signal}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="page-enter space-y-3">
    <ScreenHeader eyebrow="Beyond the application" title="Discover" description="High-signal programs, competitions and official university deadlines in one place." onBack={() => navigate("home")} />
    <Card className="discover-hero"><div><Tag tone="cyan">Open to every student</Tag><h2>Find the opportunity that proves your direction.</h2><p>Filter by what you want to build—not by what sounds impressive.</p></div><div className="orbit-mark"><Compass size={29} /></div></Card>
    <section><div className="section-title"><h2>Deadline runway</h2><span>Official sources</span></div><div className="deadline-scroll">{deadlines.map((item) => { const days = Math.max(0, Math.ceil((new Date(`${item.date}T23:59:59`).getTime() - Date.now()) / 86400000)); return <button className={`deadline-card deadline-${item.color}`} key={item.school} onClick={() => openOfficial(item.url)}><div className="deadline-campus"><span>{item.mark}</span><small>{days} days</small></div><strong>{item.school}</strong><span>{item.round} · {item.display}</span><small>Open official page <ArrowUpRight size={12} /></small></button>; })}</div><p className="verification-note">Dates are planning references for the 2026–27 cycle. Verify your exact round and applicant type on the official page.</p></section>
    <section><div className="section-title"><h2>Programs & opportunities</h2><span>{visible.length} of {opportunities.length}</span></div><div className="opportunity-search"><Search size={17} /><input aria-label="Search opportunities" placeholder="Research, writing, business…" value={query} onChange={(event) => setQuery(event.target.value)} /></div><div className="filter-row">{["All", "STEM", "Research", "Business", "Writing", "Global", "Service"].map((item) => <button className={filter === item ? "active" : ""} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="opportunity-list">{visible.map((item, index) => <button key={item.title} onClick={() => openOfficial(item.url)}><span className="opportunity-rank">{String(index + 1).padStart(2, "0")}</span><span><Tag tone="cyan">{item.type}</Tag><strong>{item.title}</strong><small>{item.fit}</small><em>{item.access} · {item.signal}</em></span><ArrowUpRight size={18} /></button>)}</div><p className="verification-note">Every item opens its official source. Eligibility, dates and costs can change, so verify the current cycle before applying.</p></section>
  </div>;
}

export function PrepHubScreen({ navigate }: { navigate: Navigate }) {
  const [streak, setStreak] = useState<PracticeStreak | null>(null);
  useEffect(() => { void api.get<PracticeStreak>("/api/practice/streak").then(setStreak).catch(() => undefined); }, []);
  const cards = [
    { title: "SAT Quest", description: "Original mini-tests, instant reasoning feedback and AI error repair", icon: Calculator, screen: "sat" as const, accent: "violet" },
    { title: "IELTS Skill Arcade", description: "Four interactive skill missions plus examiner-style coaching", icon: Languages, screen: "ielts" as const, accent: "cyan" },
    { title: "School Fit Map", description: "30-university atlas with profile-aware research tiers", icon: GraduationCap, screen: "school" as const, accent: "green" },
    { title: "Application Flight Plan", description: "Dependencies, milestones, risk radar and saved progress", icon: CalendarDays, screen: "plan" as const, accent: "orange" },
  ];
  return <div className="page-enter space-y-3"><ScreenHeader eyebrow="Practice with a purpose" title="Prep Lab" description="Choose a short practice set or work on your application." onBack={() => navigate("tools")} /><PracticeStreakCard streak={streak} /><Card className="prep-hero"><div className="prep-signal"><Target size={23} /></div><div><Tag tone="good">Practice, then review</Tag><h2>Make one focused move today.</h2><p>Practise a skill, review your mistakes, or build your plan.</p></div></Card><div className="prep-grid">{cards.map(({ title, description, icon: Icon, screen, accent }) => <button className={`prep-card prep-${accent}`} key={screen} onClick={() => navigate(screen)}><span><Icon size={23} /></span><strong>{title}</strong><small>{description}</small><em>Open lab <ArrowUpRight size={14} /></em></button>)}</div></div>;
}

type CoachMode = "brainstorm" | "rewrite";
export function AICoachScreen({ navigate, initialMode = "brainstorm" }: { navigate: Navigate; initialMode?: CoachMode }) {
  const [mode, setMode] = useState<CoachMode>(initialMode);
  const [topic, setTopic] = useState("personal_statement");
  const [goal, setGoal] = useState("");
  const [content, setContent] = useState(""); const submission = useSubmission();

  const [result, setResult] = useState<Record<string, unknown> | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  async function run() { setLoading(true); setError(""); setResult(null); try { const data = await api.analyze<{ result: Record<string, unknown> }>("/api/coach", { mode, topic, goal: goal || null, content }, submission.attachment); setResult(data.result); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not run the coach."); } finally { setLoading(false); } }
  return <div className="page-enter space-y-3"><ScreenHeader eyebrow="Your creative co-pilot" title={mode === "brainstorm" ? "Brainstorm Studio" : "Rewrite Studio"} description={mode === "brainstorm" ? "Find distinctive directions grounded in your real life." : "Strengthen the writing while keeping every fact and your voice true."} onBack={() => navigate("tools")} /><Card><Segmented value={mode} onChange={(value) => { setMode(value); setResult(null); }} options={[{ value: "brainstorm", label: "Brainstorm ideas" }, { value: "rewrite", label: "Rewrite my text" }]} /><div className="coach-mode-note"><span>{mode === "brainstorm" ? <BrainCircuit size={21} /> : <PenLine size={21} />}</span><div><strong>{mode === "brainstorm" ? "Four distinct directions, grounded in your life" : "A stronger version without invented facts"}</strong><small>{mode === "brainstorm" ? "We look for moments, tensions and proof—not generic topics." : "Voice, specificity and structure improve while your truth stays fixed."}</small></div></div><Select label="What are we working on?" value={topic} onChange={(event) => setTopic(event.target.value)}><option value="personal_statement">Personal statement</option><option value="supplemental">Supplemental essay</option><option value="extracurricular">Extracurricular description</option><option value="portfolio">Portfolio / project</option><option value="general">Other application writing</option></Select><Input label="Your goal" placeholder={mode === "brainstorm" ? "e.g. Find a non-cliché Common App direction" : "e.g. Make this more specific and natural"} value={goal} onChange={(event) => setGoal(event.target.value)} /><SubmissionInput disabled={loading} submission={submission} label={mode === "brainstorm" ? "Tell me about yourself and the situation" : "Text to improve"} rows={12} placeholder={mode === "brainstorm" ? "Share real experiences, interests, conflicts, choices, people, places and details you remember…" : "Paste the complete paragraph, essay or activity description…"} value={content} onChange={(event) => setContent(event.target.value)} hint={"Your saved portfolio is added automatically"} />{error ? <ErrorBanner message={error} /> : null}<Button className="w-full mt-4" loading={loading} disabled={!submission.ready(content, 20)} onClick={() => void run()}>{mode === "brainstorm" ? <Lightbulb size={18} /> : <Sparkles size={18} />}{mode === "brainstorm" ? "Build My Idea Map" : "Rewrite Strategically"}</Button></Card>{result ? <Card className="result-card"><Tag tone="good">{mode === "brainstorm" ? "Idea map" : "Elevated version"}</Tag><h2 className="mt-3">{String(result.headline || "Your result")}</h2><StructuredResult result={result} /></Card> : null}</div>;
}

type SATSection = "math" | "reading_writing";
type SATMode = "study_plan" | "mistake_lab";
const satSkills: Record<SATSection, string[]> = { math: ["Algebra", "Advanced math", "Problem solving", "Geometry", "Timing"], reading_writing: ["Craft & structure", "Information & ideas", "Grammar", "Expression of ideas", "Timing"] };

export function SATStudioScreen({ navigate, onChanged }: { navigate: Navigate; onChanged: () => void }) {
  const [section, setSection] = useState<SATSection>("math");
  const [mode, setMode] = useState<SATMode>("study_plan");
  const [current, setCurrent] = useState(""); const [target, setTarget] = useState(""); const [weak, setWeak] = useState<string[]>([]); const [content, setContent] = useState(""); const submission = useSubmission(); const [result, setResult] = useState<Record<string, unknown> | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function run() { setLoading(true); setError(""); setResult(null); try { const data = await api.analyze<{ result: Record<string, unknown> }>("/api/sat/coach", { section, mode, current_score: current ? Number(current) : null, target_score: target ? Number(target) : null, weak_skills: weak, content: content || null }, mode === "mistake_lab" ? submission.attachment : null); setResult(data.result); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not build your SAT mission."); } finally { setLoading(false); } }
  return <><Card><Segmented value={section} onChange={value => { setSection(value); setWeak([]); setCurrent(""); setTarget(""); setResult(null); }} options={[{ value: "math", label: "Math" }, { value: "reading_writing", label: "Reading & Writing" }]} /><Segmented value={mode} onChange={setMode} options={[{ value: "study_plan", label: "7-day sprint" }, { value: "mistake_lab", label: "Mistake lab" }]} /><div className="form-grid two"><Input label="Current section score" type="number" min={200} max={800} placeholder="620" value={current} onChange={(event) => setCurrent(event.target.value)} /><Input label="Target section score" type="number" min={200} max={800} placeholder="720" value={target} onChange={(event) => setTarget(event.target.value)} /></div><div className="field"><span className="field-label">Skills that feel hardest</span><div className="skill-chips">{satSkills[section].map((skill) => <button className={weak.includes(skill) ? "active" : ""} key={skill} onClick={() => setWeak((items) => items.includes(skill) ? items.filter((item) => item !== skill) : [...items, skill])}>{weak.includes(skill) ? <Check size={13} /> : null}{skill}</button>)}</div></div>{mode === "mistake_lab" ? <><SubmissionInput disabled={loading} submission={submission} label="Question, your attempt, and what went wrong" rows={9} placeholder="Paste the question text you are allowed to use, your reasoning, answer choices, and the correct answer if known…" value={content} onChange={(event) => setContent(event.target.value)} hint={"The coach teaches the reasoning, not just the answer"} /></> : <p className="tool-explainer">Your sprint mixes skill repair, spaced review, timed transfer and a short error-log ritual.</p>}{error ? <ErrorBanner message={error} /> : null}<Button className="w-full" loading={loading} disabled={mode === "mistake_lab" && !submission.ready(content, 20)} onClick={() => void run()}><Target size={18} />{mode === "study_plan" ? "Build My 7-Day Sprint" : "Diagnose This Mistake"}</Button></Card>{result ? <Card className="result-card"><Tag tone="good">SAT coach</Tag><h2 className="mt-3">{String(result.headline || "Your SAT mission")}</h2><StructuredResult result={result} /></Card> : null}</>;
}

export function FeedbackScreen({ navigate }: { navigate: Navigate }) {
  const [category, setCategory] = useState("idea"); const [rating, setRating] = useState(5); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [sent, setSent] = useState(false);
  async function submit() { setLoading(true); setError(""); try { await api.post("/api/feedback", { category, rating, message }); setSent(true); window.Telegram?.WebApp.HapticFeedback?.notificationOccurred("success"); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not send feedback."); } finally { setLoading(false); } }
  if (sent) return <div className="page-enter"><ScreenHeader eyebrow="Message received" title="Thank you." description="Your feedback was saved and sent directly to the UniVentureAI team." onBack={() => navigate("home")} /><Card className="feedback-thanks"><span><Check size={26} /></span><h2>You just made the next version better.</h2><p>We read specific examples first—especially bugs and confusing moments.</p><Button variant="secondary" onClick={() => navigate("home")}>Back to Home</Button></Card></div>;
  return <div className="page-enter space-y-3"><ScreenHeader eyebrow="Build UniVentureAI with us" title="Send Feedback" description="A bug, idea or confusing moment—tell us honestly. It reaches the team." onBack={() => navigate("home")} /><Card><div className="feedback-rating"><span>How useful is the app today?</span><div>{[1,2,3,4,5].map((value) => <button className={rating === value ? "active" : ""} key={value} onClick={() => setRating(value)}>{value}</button>)}</div></div><Select label="What is this about?" value={category} onChange={(event) => setCategory(event.target.value)}><option value="idea">Feature idea</option><option value="bug">Something is broken</option><option value="confusing">Something is confusing</option><option value="love">Something works really well</option></Select><Textarea label="Your message" rows={8} placeholder="What happened? What did you expect? What would make it better?" value={message} onChange={(event) => setMessage(event.target.value)} />{error ? <ErrorBanner message={error} /> : null}<Button className="w-full" loading={loading} disabled={message.trim().length < 5} onClick={() => void submit()}><Send size={18} />Send to UniVentureAI</Button></Card><Card tone="cyan" className="feedback-note"><MessageCircleMore size={21} /><div><strong>Short is fine. Specific is gold.</strong><p>Your Telegram ID is attached so the team can investigate account-specific bugs; your public name is not required.</p></div></Card></div>;
}
